language: rust
cache: cargo

rust:
  - nightly-2018-04-01

before_install:
  # hot fix for https://github.com/ggez/ggez/issues/100
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      sudo apt-get -qq update
      && sudo apt-get install -y libasound2-dev;
    fi

matrix:
  include:
    # Linux 64bit
    - env: TARGET=x86_64-unknown-linux-gnu
      os: linux

install:
  - rustup self update
  - rustup target add $TARGET; true

script:
  - ./ci/install_cargo_web.sh
  - cargo build --target $TARGET --verbose
  - cargo build --target $TARGET --verbose --examples
  - cargo web build --example basic 
  - cargo web build --example boxes
  - cargo web build --example framebuffer
  - cargo web build --example meshobj
  - cargo web build --example postprocessing
  - cargo web build --example scenenodes
  - cargo web build --example shadow
  - cargo web build --example skybox
  - cargo web build --example sound
  - cargo web build --example sponza
  - cargo web build --example basic --release
