[package]
name = "unrust"
version = "0.1.0"
authors = ["Edwin Cheng <edwin0cheng@gmail.com>"]

[dependencies]
nalgebra   = "0.13"
nphysics3d = "0.7.2"
ncollide = "0.13.0"
webgl = {path="webgl"}
uni-app = {path="uni-app"}
uni-glsl = {path="uni-glsl"}
uni-snd = {path="uni-snd"}
futures = "0.1"
obj = "0.8.2"
alga = "0.5"

[dependencies.lazy_static]
version = "1.0"
features = ["nightly"]

# Image related dependencies
[dependencies.image]
# version = "*"
git = "https://github.com/edwin0cheng/image"
branch = "impl_tga_read_scanline"
default-features = false
features = ["png_codec", "tga"]

[replace]
"rustc-serialize:0.3.24" = { path = "wasm-rustc-serialize" }

# wasm compilation isn't currently compatible with incremental compilation
# see https://github.com/rust-lang/rust/issues/47643
# [profile.dev]
# incremental = false

[dev-dependencies]
bitflags = "1.0"